from hh.render.config.config_registry import register_label

@register_label('activities',                        'Activities:',                 '📋')
@register_label('activity',                          'Activity:',                   '📋')
@register_label('blank_emoji',                       '',                            '  ')
@register_label('content',                           'Content:',                    '📄')
@register_label('created_at',                         'Created At:',                  '⏰')
@register_label('count',                              'Count:',                       '🔢')
@register_label('error',                              'Error:',                       '❌')
@register_label('info',                               'Info:',                        '📊')
@register_label('success',                            'Success:',                     '✅')
@register_label('debug',                             'Debug:',                       '🐛')
@register_label('debug_header',                      'Debug Trace',                 '🔍')
@register_label('docket',                           'Docket:',                     '💼')
@register_label('doing',                             'Doing:',                      '🔄')
@register_label('done',                              'Done:',                       '✅')
@register_label('file',                              'File:',                       '📁')
@register_label('filing_cabinet',                    'Filing Cabinet:',             '📂')
@register_label('kind',                              'Kind:',                       '🔸')
@register_label('linked_items',                      'Linked Items:',              '🔗')
@register_label('log',                               'Log:',                        '🔸')
@register_label('mysql',                             'MySQL:',                      '🐬')
@register_label('notes',                             'Notes:',                      '📄')
@register_label('number',                           'Number:',                     '🔢')
@register_label('sidecar_link',                      'Sidecar Link:',               '🔗')
@register_label('sort_order',                        'Sort Order:',                 '# ')
@register_label('sql',                               'SQL:',                        '📝')
@register_label('statistics',                        'Statistics:',                 '📊')
@register_label('status',                           'Status:',                     '🔸')
@register_label('step_tree',                         'Step Tree:',                  '📍')
@register_label('tab',                               '',                            '  ')
@register_label('todo',                              'Todo:',                       '🔲')
@register_label('trace_in',                          'In:',                         '🔲')
@register_label('trace_out',                         'Out:',                        '✅')
@register_label('warn',                              'Warning:',                     '🚨')
@register_label('action',                            'Action:'                      )
@register_label('action_args',                       'Action Args:'                 )
@register_label('activity_content',                   'Content:'                     )
@register_label('activity_id',                       'Activity ID:'                 )
@register_label('activity_kind',                     'Kind:'                        )
@register_label('activity_logs',                      'Activity Logs:'               )
@register_label('activity_timestamp',                'Timestamp:'                   )
@register_label('affected_rows',                     'Affected Rows:'               )
@register_label('agent_purge_header',                'Agent Purge'                  )
@register_label('agent_state',                       'Agent State:'                 )
@register_label('agent_tree',                        'Agent Tree:'                  )
@register_label('agent_tree_header',                 'Agent Tree'                   )
@register_label('ask_context',                       'Ask Context:'                 )
@register_label('chars',                             'more chars:'                  )
@register_label('deep_mode',                         'Deep Mode:'                   )
@register_label('docket_context',                    'Docket Context:'              )
@register_label('from',                              'From:'                        )
@register_label('id',                                'ID:'                          )
@register_label('items',                             'items:'                       )
@register_label('keyword',                           'Keyword:'                     )
@register_label('main_header',                       '🏠 Henhouse: '                )
@register_label('more_items',                        'more items:'                  )
@register_label('mysql_errno',                       'MySQL Error Code:'            )
@register_label('mysql_message',                     'MySQL Message:'               )
@register_label('mysql_sqlstate',                    'SQL State:'                  )
@register_label('occurred',                          'occurred:'                    )
@register_label('remaining',                         'remaining:'                    )
@register_label('session',                           'Session:'                     )
@register_label('sidecar',                           'Sidecar:'                     )
@register_label('sidecar_links',                     'Sidecar Links:'               )
@register_label('sql_params',                        'SQL Parameters:'              )
@register_label('sql_query',                         'SQL Query:'                   )
@register_label('step_description',                  'Step Description:'            )
@register_label('step_id',                           'Step ID:'                     )
@register_label('step_status',                       'Step Status:'                 )
@register_label('step_title',                        'Step Title:'                  )
@register_label('step_tree_header',                  'Step Tree'                    )
@register_label('subscriptions',                     'Subscriptions:'               )
@register_label('task_context',                      'Task Context:'                )
@register_label('timeclock_punch_header',             'Timeclock Punch'             )
@register_label('timestamp',                         'Timestamp:'                   )
@register_label('title',                             'Title:'                       )
@register_label('name',                              'Name:'                        )
@register_label('work_preview_header',               'Work Preview'                )
@register_label('command',                           'Command:',                    '⌨️')
def _register_config():
    pass

