from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol
import datetime as dt


class BasePage(Protocol):
    # Core fields
    id: int
    gateway: Any
    parent: Optional[int]
    class_name: Optional[str]
    name: Optional[str]
    link: Optional[str]
    text: Optional[str]
    visibility: Optional[int]
    last_modified: Optional[dt.datetime]
    username: Optional[str]
    comments: Optional[str]
    metadata: Optional[Dict[str, Any]]
    displayStyle: Optional[int]
    viewCount: Optional[int]

    # Derived/cache fields
    display_name: Optional[str]
    prepared_text: Optional[Any]
    children_by_class: Optional[Dict[str, Any]]
    images: List[Any]
    files: List[Any]
    cache_built_at: Optional[Any]
    cache_hydrated: bool
    _cache_needs_refresh: bool

    # Cross-mixin helpers (type stubs only)
    def flag_page_modification(self, comments: str) -> bool: ...
    def _flag_cache_refresh(self) -> None: ...
    def allow_class_inside(self, class_name: str) -> bool: ...
    def validate_name(self, name: str, class_name: str, exclude_id: Optional[int] = None) -> bool: ...
    def _get_child_page_ids(self) -> List[int]: ...
    def _enqueue_maintenance_job(self, job_type: str, payload: Dict[str, Any], priority: int = 0) -> int: ...
    def get_path(self) -> Any: ...
    def get_images_data(self, rebuild: bool = False) -> List[Dict[str, Any]]: ...
    def get_files_data(self, rebuild: bool = False) -> List[Dict[str, Any]]: ...
    def _get_children_by_class(self) -> Dict[str, Any]: ...
    def get_page_data(self) -> Dict[str, Any]: ...
    def get_prepared_text(self) -> Optional[List[Dict[str, Any]]]: ...
    def modify_text(self, text: str) -> bool: ...
    def auto_link_name(self) -> bool: ...
    def allow_null_names(self) -> bool: ...
    def allow_duplicate_names(self) -> bool: ...
    def allow_inside_of(self, parent_class: str) -> bool: ...
    def can_move_to_page(self, target_page_id: int) -> bool: ...
    def _set_file_rank(self, file_id: int, current_rank: int, new_rank: int) -> bool: ...
    def _get_display_name(self) -> str: ...
    def _dump_json(self, value: Any) -> str: ...
    def _reorder_images(self) -> bool: ...
    def _set_image_rank(self, image_id: int, current_rank: int, new_rank: int) -> bool: ...
    @classmethod
    def _get_children_query(cls, parent_id: int) -> tuple[str, list]: ...

