from hh.render.config.config_registry import register_label

@register_label('promote',                            'Promote:',                     '⬆️')
@register_label('answer',                             'Answer:',                      '💬')
@register_label('onboard',                            'Onboard:',                     '🚀')
@register_label('training',                           'Training:',                    '📚')
@register_label('answers',                            'Answers:',                     '💬')
@register_label('badge',                              'Badge:',                       '🏆')
@register_label('document',                            'Document:',                    '📄')
@register_label('question',                            'Question:',                    '❓')
@register_label('recorded',                            'Recorded:',                    '📝')
@register_label('coffee',                              'Coffee:',                      '☕')
@register_label('exam',                                'Exam:',                        '📝')
@register_label('complete',                            'Complete:',                    '✅')
@register_label('role',                               'Role:',                        '👤')
@register_label('status_header',                      'Agent Status'                  )
@register_label('promote_header',                     'Agent Promotion'               )
@register_label('answer_header',                      'Training Answer'               )
@register_label('onboard_header',                     'Agent Onboarding'              )
@register_label('agent_info',                         'Agent Information:'            )
@register_label('training_progress',                  'Training Progress:'            )
@register_label('old_role',                           'Previous Role:'                )
@register_label('new_role',                           'New Role:'                     )
@register_label('promotion_successful',                'Promotion Successful:'         )
@register_label('role_training_complete',              'Role Training Complete:'       )
@register_label('badge_ts',                           'Badge Timestamp:'             )
@register_label('doc_path',                           'Document Path:'                )
@register_label('has_question',                        'Has Question:'                 )
@register_label('response_recorded',                   'Response Recorded:'            )
@register_label('coffees_done',                       'Coffees Completed:'            )
@register_label('coffees_total',                      'Total Coffees:'               )
@register_label('exams_done',                         'Exams Completed:'             )
@register_label('exams_total',                        'Total Exams:'                  )
@register_label('training_complete',                  'Training Complete:'            )
@register_label('training_gate',                        'Training Gate:'                )
@register_label('next_command',                       'Next Command:'                 )
def _register_config():
    pass

