"""Image group class - derives from TileGroup for rendering image tiles."""

from __future__ import annotations

from typing import Any, Dict, List

from hh.gateway.gateway import get_gateway
from hh.gateway.registry.debug import get_trace_in, get_trace_out, get_log, get_debug, get_warn, register_debug_init
from hh.render.html.link_helpers import create_image_link
from hh.render.html.tile_group import TileGroup
from hh.render.html.tiles import Tile
from hh.render.render import FieldConfig, TableData, render_block
from hh.render.config.config import safe_str

trace_in = lambda message=None: None
trace_out = lambda message=None: None
log = lambda message: None
debug = lambda message: None
warn = lambda message: None

@register_debug_init
def _initialize_debug():
    global trace_in, trace_out, log, debug, warn
    trace_in = get_trace_in(True)
    trace_out = get_trace_out(True)
    log = get_log(True)
    debug = get_debug(True)
    warn = get_warn(True)


class ImageGroup(TileGroup):
    """Tile group for rendering images as tiles."""
    
    def __init__(self, images_data: List[Dict[str, Any]], page_id: int, target_width: int = 300, wrapper_id: str = None, wrapper_extra_classes: str = None):
        """Initialize image group by parsing image data and creating tiles.
        
        Args:
            images_data: List of image data dicts with 'id', 'caption', 'instances', 'image_rank'
            page_id: Page ID for generating unique element IDs
            target_width: Target width for tiles (default 300)
            wrapper_id: Custom wrapper ID (if None, uses default pageImageGroup_{page_id})
            wrapper_extra_classes: Additional CSS classes for the wrapper div
        """
        trace_in()
        super().__init__(target_width=target_width)
        self.page_id = page_id
        self.page_id_str = str(page_id)
        self.content_id = wrapper_id if wrapper_id else f"pageImageGroup_{self.page_id_str}"
        self.wrapper_extra_classes = wrapper_extra_classes
        
        # Parse image data and create tiles
        for image_data in images_data:
            image_id = image_data.get('id')
            instances = image_data.get('instances', [])
            image_caption = image_data.get('caption', '')
            
            # Create image dict with instances
            image_dict = {'instances': instances}
            
            # Determine link
            link_href = create_image_link(image_id) if image_id else '#'
            
            # Create and add tile
            tile = Tile(
                image=image_dict,
                text=image_caption,
                link=link_href,
                metadata={},
                target_width=target_width
            )
            self.add_tile(tile)
        
        log(f"Initialized ImageGroup with {len(self.tiles)} images for page {page_id}")
        trace_out()
    
    def finalize_output(self, html_content: str) -> str:
        """Finalize output by wrapping in content div.
        
        Note: Headers are generated by show_page and prepended separately.
        This method just wraps the content div.
        """
        trace_in()
        
        # Build class string: always "content pageImageGroup", plus any extra classes
        class_parts = ['content', 'pageImageGroup']
        if self.wrapper_extra_classes:
            class_parts.append(self.wrapper_extra_classes)
        class_str = ' '.join(class_parts)
        
        # Wrap content in div with unique ID, with clearboth inside to contain floats
        content_html = f'<div id="{self.content_id}" class="{class_str}">{html_content}<div class="clearboth"></div></div>'
        
        log(f"Finalized image group output for page {self.page_id}")
        trace_out()
        return content_html
