"""Page group class - derives from TileGroup for rendering page tiles."""

from __future__ import annotations

from typing import Any, Dict, List

from hh.gateway.gateway import get_gateway
from hh.gateway.registry.debug import get_trace_in, get_trace_out, get_log, get_debug, get_warn, register_debug_init
from hh.render.html.link_helpers import create_page_link
from hh.render.html.tile_group import TileGroup
from hh.render.html.tiles import Tile
from hh.render.render import FieldConfig, TableData, render_block
from hh.render.config.config import safe_str

trace_in = lambda message=None: None
trace_out = lambda message=None: None
log = lambda message: None
debug = lambda message: None
warn = lambda message: None

@register_debug_init
def _initialize_debug():
    global trace_in, trace_out, log, debug, warn
    trace_in = get_trace_in(True)
    trace_out = get_trace_out(True)
    log = get_log(True)
    debug = get_debug(True)
    warn = get_warn(True)


def snake_case_to_title_case(class_name: str) -> str:
    """Convert snake_case class name to human-readable Title Case.
    
    Args:
        class_name: Snake case class name (e.g., "source_code_file")
    
    Returns:
        Title case pluralized name (e.g., "Source Code Files")
    """
    trace_in()
    # Replace underscores with spaces and title case
    words = class_name.replace('_', ' ').split()
    title_words = [word.capitalize() for word in words]
    result = ' '.join(title_words)
    
    # Pluralize (simple: add 's' if not already plural)
    if not result.endswith('s'):
        result += 's'
    
    log(f"Converted '{class_name}' to '{result}'")
    trace_out()
    return result


class PageGroup(TileGroup):
    """Tile group for rendering pages as tiles."""
    
    def __init__(
        self,
        children_data: List[Dict[str, Any]],
        page_id: int,
        class_name: str,
        target_width: int = 300,
        wrapper_id: str = None,
        wrapper_extra_classes: str = None
    ):
        """Initialize page group by parsing page data and creating tiles.
        
        Args:
            children_data: List of child page data dicts
            page_id: Parent page ID for generating unique element IDs
            class_name: Child page class name (e.g., "source_code_file")
            target_width: Target width for tiles (default 300)
            wrapper_id: Custom wrapper ID (if None, uses default child_pages_{class_name}_{page_id})
            wrapper_extra_classes: Additional CSS classes for the wrapper div
        """
        trace_in()
        super().__init__(target_width=target_width)
        self.page_id = page_id
        self.class_name = class_name
        self.page_id_str = str(page_id)
        self.class_name_safe = class_name.replace('_', '-')
        self.content_id = wrapper_id if wrapper_id else f"child_pages_{self.class_name_safe}_{self.page_id_str}"
        self.wrapper_extra_classes = wrapper_extra_classes
        
        # Parse page data and create tiles
        for page_data in children_data:
            child_id = page_data.get('id')
            display_name = page_data.get('display_name', '')
            if not display_name:
                display_name = "(no name)"
            
            # Get first image if available
            images = page_data.get('images', [])
            image_dict = {}
            if images and len(images) > 0:
                first_image = images[0]
                instances = first_image.get('instances', [])
                if instances:
                    image_dict = {'instances': instances}
            
            # Determine link
            link_href = create_page_link(child_id) if child_id else '#'
            
            # Create and add tile
            tile = Tile(
                image=image_dict,
                text=display_name,
                link=link_href,
                metadata={},
                target_width=target_width
            )
            self.add_tile(tile)
        
        log(f"Initialized PageGroup with {len(self.tiles)} pages for class '{class_name}' on page {page_id}")
        trace_out()
    
    def finalize_output(self, html_content: str) -> str:
        """Finalize output by wrapping in content div.
        
        Note: Headers are generated by show_page and prepended separately.
        This method just wraps the content div.
        """
        trace_in()
        
        # Build class string: always "content pageGroup", plus any extra classes
        class_parts = ['content', 'pageGroup']
        if self.wrapper_extra_classes:
            class_parts.append(self.wrapper_extra_classes)
        class_str = ' '.join(class_parts)
        
        # Wrap content in div with unique ID, with clearboth inside to contain floats
        content_html = f'<div id="{self.content_id}" class="{class_str}">{html_content}<div class="clearboth"></div></div>'
        
        log(f"Finalized page group output for class '{self.class_name}' on page {self.page_id}")
        trace_out()
        return content_html
