from hh.render.config.config_registry import register_label

@register_label('channels',                           'Channels:',                    '📡')
@register_label('message',                            'Message ID:',                  '📧')
@register_label('message_from',                      'From:',                        '📤')
@register_label('message_to',                        'To:',                          '📥')
@register_label('microlog',                           'Microlog:',                    '🔔')
@register_label('pointer',                           'Pointer:',                     '👉')
@register_label('queue',                              'Queue:',                       '📫')
@register_label('subscription',                       'Subscription:',                 '📡')
@register_label('target',                             'Target:',                      '🎯')
@register_label('arrow',                             'Arrow:',                       '➡️')
@register_label('channel',                            'Channel:',                     '📺')
@register_label('operator',                          'Operator:',                    '⚙️')
@register_label('messages',                           'Messages:',                    '💬')
@register_label('characters',                         'Characters:',                  '🔤')
@register_label('peek_header',                       'Watercooler Queue Sip/Peek'     )
@register_label('sip_header',                        'Watercooler Sip'                )
@register_label('gossip_header',                     'Watercooler Gossip'             )
@register_label('gulp_header',                       'Watercooler Gulp Export'        )
@register_label('subscription_header',                 'Subscription Operations'        )
@register_label('message_channel',                    'Channel:'                       )
@register_label('message_kind',                       'Kind:'                          )
@register_label('queued_timestamp',                   'Queued:'                        )
@register_label('message_timestamp',                  'Sent:'                          )
@register_label('subscription_target_type',           'Target Type:'                   )
@register_label('subscription_target_id',             'Target ID:'                     )
@register_label('subscription_target_title',          'Target Title:'                  )
@register_label('message_count',                      'Message Count:'                 )
@register_label('output_file',                        'Output File:'                   )
@register_label('export_time',                        'Export Time:'                   )
@register_label('message_index',                      'Message #:'                     )
@register_label('direction',                          'Direction:'                     )
@register_label('messages_preview',                   'Messages Preview'               )
@register_label('no_messages',                        'No messages found'              )
def _register_config():
    pass

