from hh.render.config.config_registry import register_label

@register_label('http_deploy_header',                 'HTTP Deployment Status',         '🌐')
@register_label('http_deploy_ssl_header',             'HTTP SSL Deployment Status',    '🔒')
@register_label('http_status_header',                 'HTTP Site Deployment Status',    '📊')
@register_label('domain_header',                     'Domain:',                        '🌐')
@register_label('certificate_path',                   'Certificate Path:',              '🔑')
@register_label('nginx_active',                       'Nginx Active:',                  '✅')
@register_label('nginx_deployed',                     'Nginx Config Deployed:',          '🌐')
@register_label('port',                              'Port:',                          '🔌')
@register_label('http_config_path',                  'Config File Path:',              '🌍')
@register_label('main_domain',                       'Main Domain:',                   '🌐')
@register_label('subdomain',                         'Subdomain:',                     '🔗')
@register_label('http_remove_header',                'HTTP Removal Status',            '🧹')
@register_label('active_henhouse_header',             'Active Henhouse Sites',          '✅')
@register_label('available_henhouse_header',          'Available Henhouse Sites',       '📦')
@register_label('active_other_header',                'Active Other Sites',             '🌍')
@register_label('available_other_header',             'Available Other Sites',          '📁')
@register_label('service_header',                     'Service Status:',                '👋')
@register_label('active_service',                      'Service (Active):',              '✅')
@register_label('inactive_service',                   'Service (Inactive):',            '❌')
@register_label('summary_header',                     'Summary:',                       '📈')
@register_label('site_header',                        'Site:',                          '🌐')
@register_label('site_http',                          'HTTP:',                          '🌐')
@register_label('site_https',                         'HTTP + SSL:',                    '🔒')
@register_label('active_henhouse',                    'Active Henhouse:',               '✅')
@register_label('available_henhouse',                 'Available Henhouse:',            '📦')
@register_label('active_other',                        'Active Other:',                 '🌍')
@register_label('available_other',                    'Available Other:',               '📁')
@register_label('js_whitelist',                       'JS Whitelist:',                  '📜')
@register_label('css_whitelist',                      'CSS Whitelist:',                 '🎨')
@register_label('misc_whitelist',                     'Misc Whitelist:',                '📦')
@register_label('context_whitelist',                   'Context Whitelist:',              '📂')
@register_label('bind_ips',                           'Bound to:',                       '🔗')
@register_label('client_ip_access',                   'Client IP Access:',                '🛡️')
@register_label('project_header',                     'Project:',                        '📁')
@register_label('deploy_header',                      'Deployment Status',               '🚀')
@register_label('code_deployed',                      'Code Deployed:',                  '✅')
@register_label('deployment_cleaned',                 'Deployment Cleaned:',             '🧹')
@register_label('cache_cleaned',                      'Cache Cleaned:',                  '🧹')
@register_label('flask_deployed',                     'Flask App Deployed:',             '🌐')
@register_label('context_deployed',                   'Context Deployed:',               '📂')
@register_label('ownership_set',                      'Ownership Set:',                  '👤')
@register_label('cache_permissions',                  'Cache Permissions:',              '🔒')
@register_label('js_count',                           'JS Files Deployed:',              '📜')
@register_label('css_count',                          'CSS Files Deployed:',             '🎨')
@register_label('misc_count',                         'Misc Files Deployed:',            '📦')
@register_label('flask_restart',                      'Flask Restart:',                 '🔁')
@register_label('maintenance_restart',                'Maintenance Restart:',            '🧰')
@register_label('project_info',                       'Project Info:',                   'ℹ️')
@register_label('remove_header',                      'Removal Status',                  '🗑️')
@register_label('deployment_path',                    'Deployment Path:',                '📁')
@register_label('domains_removed',                    'Domains Removed:',                '✅')
@register_label('domains_failed',                     'Domains Failed:',                 '❌')
@register_label('flask_stopped',                      'Flask Stopped:',                  '🛑')
@register_label('maintenance_stopped',              'Maintenance Stopped:',             '🛑')
@register_label('files_removed',                      'Files Removed:',                  '🗑️')
@register_label('manifest_cleared',                    'Manifest Cleared:',              '🧹')
@register_label('nginx_enabled_sites',                'Nginx Enabled Sites:',            '🌐')
def _register_config():
    pass

