import subprocess
from pathlib import Path
from typing import Dict, Any, Optional
from hh.gateway.registry.registry import register_action
from hh.gateway.registry.registry import register_command
from hh.gateway.gateway import get_gateway
from hh.gateway.registry.debug import get_trace_in, get_trace_out, get_log, get_debug, get_warn, register_debug_init
from hh.gateway.response.json_standard import success_payload
from hh.gateway.error.error_store import report_error, is_error

trace_in = lambda message=None: None
trace_out = lambda message=None: None
log = lambda message: None
debug = lambda message: None
warn = lambda message: None

@register_debug_init
def _initialize_debug():
    global trace_in, trace_out, log, debug, warn
    trace_in = get_trace_in(True)
    trace_out = get_trace_out(True)
    log = get_log(True)
    debug = get_debug(True)
    warn = get_warn(True)

def detect_project_name() -> str:
    """Detect project name from current directory."""
    try:
        gateway = get_gateway()
        if not gateway or not gateway.os:
            return "henhouse"
        cwd = gateway.os.get_cwd()
        if cwd.startswith('/srv/'):
            parts = cwd.split('/')
            if len(parts) >= 3:
                return parts[2]
        else:
            current_path = Path(cwd)
            while current_path != current_path.parent:
                hh_dir = current_path / 'hh'
                if hh_dir.exists() and hh_dir.is_dir():
                    return current_path.name
                current_path = current_path.parent
        return "henhouse"
    except Exception:
        return "henhouse"

def create_nginx_ssl_config(domain: str, project_name: str, certificate_path: Optional[str] = None) -> str:
    """Generate Nginx SSL configuration for the domain and its subdomains (Stage 2)."""
    trace_in()
    try:
        # Default certificate path if not specified
        if not certificate_path:
            certificate_path = f"/etc/letsencrypt/live/{domain}"
        
        # Import helpers
        from hh.deploy.http.nginx_whitelist import generate_nginx_static_locations
        from hh.deploy.http.nginx_config_helpers import (
            generate_https_server_block, detect_flask_ports, 
            generate_http_redirect_block,
            get_server_configs
        )
        
        # Get static locations
        whitelist_result = generate_nginx_static_locations(project_name)
        static_locations = whitelist_result['config'] if isinstance(whitelist_result, dict) else whitelist_result

        # Add root-level mappings for files in MISC_WHITELIST (e.g., /favicon.ico)
        try:
            from hh.deploy.conf.misc_whitelist import MISC_WHITELIST
            from pathlib import Path as _P
            misc_blocks = []
            for item in MISC_WHITELIST:
                filename = _P(item).name
                if not filename:
                    continue
                misc_blocks.append(f"""    location /{filename} {{
        alias /srv/{project_name}/site/{filename};
        expires off;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }}""")
            if misc_blocks:
                static_locations = f"{static_locations}\n\n" + "\n\n".join(misc_blocks)
        except Exception:
            pass
        
        config_lines = [
            "# Generated by henhouse deploy-ssl system",
            "# Stage 2: HTTPS configuration (after SSL certificates)",
            "",
        ]
        
        # Add HTTP to HTTPS redirect for all domains
        all_domains = [domain, f'www.{domain}', f'admin.{domain}', f'panel.{domain}']
        config_lines.extend(generate_http_redirect_block(all_domains))
        
        # Detect media port
        ports = detect_flask_ports(project_name)
        media_port = ports.get('media', 5005)
        
        # Get server configurations
        servers = get_server_configs(domain, project_name)
        
        # Generate HTTPS block for main site (guest tier)
        main_server = servers[0]
        block_lines = generate_https_server_block(
            main_server['names'],
            main_server['port'],
            static_locations,
            certificate_path,
            main_server['label'],
            rate_limit="general",
            project_name=project_name,
            media_port=media_port
        )
        config_lines.extend(block_lines)
        
        # Generate separate HTTPS blocks for admin and panel
        for server in servers[1:]:  # Skip main site (index 0)
            block_lines = generate_https_server_block(
                server['names'],
                server['port'],
                static_locations,
                certificate_path,
                server['label'],
                rate_limit="admin",
                project_name=project_name,
                media_port=media_port
            )
            config_lines.extend(block_lines)
        
        config = '\n'.join(config_lines)
        trace_out()
        return config
    except Exception as e:
        warn(f"Failed to generate Nginx SSL config: {e}")
        trace_out()
        return ""

def install_nginx_ssl_config(domain: str, project_name: str, certificate_path: Optional[str] = None) -> bool:
    """Create Nginx SSL configuration file and enable site."""
    trace_in()
    try:
        # Generate configuration
        config_content = create_nginx_ssl_config(domain, project_name, certificate_path)
        if not config_content:
            warn("Failed to generate SSL configuration")
            trace_out()
            return False
        
        # Write to sites-available (overwrites existing HTTP config)
        config_file = Path(f'/etc/nginx/sites-available/{domain}')
        config_file.write_text(config_content)
        log(f"Nginx SSL config written to: {config_file}")
        
        # Ensure symlink exists in sites-enabled
        enabled_file = Path(f'/etc/nginx/sites-enabled/{domain}')
        if not enabled_file.exists():
            enabled_file.symlink_to(config_file)
            log(f"Symlink created: {enabled_file}")
        else:
            log(f"Symlink already exists: {enabled_file}")
        
        # Test Nginx configuration
        test_result = subprocess.run(['nginx', '-t'], capture_output=True, text=True)
        if test_result.returncode != 0:
            warn(f"Nginx configuration test failed: {test_result.stderr}")
            trace_out()
            return False
        
        log("Nginx SSL configuration test passed")
        
        # Reload Nginx
        reload_result = subprocess.run(['systemctl', 'reload', 'nginx'], capture_output=True, text=True)
        if reload_result.returncode != 0:
            # Try restart instead
            restart_result = subprocess.run(['systemctl', 'restart', 'nginx'], capture_output=True, text=True)
            if restart_result.returncode != 0:
                warn(f"Failed to reload/restart Nginx: {restart_result.stderr}")
                trace_out()
                return False
            log("Nginx restarted successfully")
        else:
            log("Nginx reloaded successfully")
        
        trace_out()
        return True
        
    except Exception as e:
        warn(f"Failed to install Nginx SSL configuration: {e}")
        trace_out()
        return False

def check_nginx_status() -> Dict[str, Any]:
    """Check current Nginx status."""
    trace_in()
    try:
        status_result = subprocess.run(['systemctl', 'is-active', 'nginx'], 
                                       capture_output=True, text=True)
        is_active = status_result.returncode == 0 and status_result.stdout.strip() == 'active'
        
        # Get enabled sites
        enabled_sites = []
        sites_enabled_dir = Path('/etc/nginx/sites-enabled')
        if sites_enabled_dir.exists():
            for site_file in sites_enabled_dir.iterdir():
                if site_file.is_symlink() or not site_file.suffix:
                    enabled_sites.append(site_file.name)
        
        result = {
            'is_active': is_active,
            'enabled_sites': enabled_sites
        }
        log(f"Nginx status: active={is_active}, sites={len(enabled_sites)}")
        trace_out()
        return result
        
    except Exception as e:
        warn(f"Failed to check Nginx status: {e}")
        trace_out()
        return {'is_active': False, 'enabled_sites': []}

@register_action('http_deploy_ssl')
@register_command('http_deploy_ssl')
def http_deploy_ssl() -> bool:
    trace_in()
    gateway = get_gateway()
    if not gateway:
        warn("No gateway available")
        trace_out()
        return False

    # Check if running in deployed Unix environment with privileges
    if not gateway.os or not gateway.os.require_privileged():
        trace_out()
        return False

    # Get domain argument
    domain = gateway.get_arg('domain')
    if not domain:
        warn("Domain argument required")
        report_error("action", "Domain argument required")
        trace_out()
        return False
    
    # Get optional certificate path
    certificate_path = gateway.get_arg('cert_path')
    
    # Detect project name
    project_name = detect_project_name()
    log(f"Project: {project_name}")
    
    log(f"Starting SSL deployment for domain: {domain}")

    # Install Nginx SSL configuration
    config_installed = False
    try:
        if install_nginx_ssl_config(domain, project_name, certificate_path):
            config_installed = True
            log("Nginx SSL configuration installed successfully")
        else:
            warn("Nginx SSL configuration installation failed")
            report_error("action", "Nginx SSL configuration installation failed")
    except Exception as e:
        warn(f"Failed to install Nginx SSL configuration: {e}")
        report_error("action", f"Failed to install Nginx SSL configuration: {e}")

    # Check Nginx status
    nginx_status = check_nginx_status()

    # Get whitelist summary for display
    from hh.deploy.http.nginx_whitelist import generate_nginx_static_locations
    whitelist_result = generate_nginx_static_locations(project_name)
    whitelist_summary = whitelist_result.get('summary', {}) if isinstance(whitelist_result, dict) else {}

    # Final result
    result = not is_error()
    if result:
        log("SSL deployment completed successfully")
        result_data = {
            "domain": domain,
            "project_name": project_name,
            "config_installed": config_installed,
            "nginx_active": nginx_status.get('is_active', False),
            "port": 443,
            "config_file_path": f"/etc/nginx/sites-available/{domain}",
            "certificate_path": certificate_path or f"/etc/letsencrypt/live/{domain}",
            "main_domain": domain,
            "subdomains": [f"www.{domain}", f"admin.{domain}", f"panel.{domain}"],
            "whitelist_summary": whitelist_summary,
            "status": "deployed",
            "stage": "2"
        }
        gateway.response.set_action_response(success_payload(result_data))
    else:
        log("SSL deployment encountered problems")

    # Clear registry cache
    from hh.deploy.cache.cache_cleanup_registry import clean_all_caches
    clean_all_caches()
    trace_out()
    return result


