import os
import configparser
import json
import datetime
from pathlib import Path
from typing import Dict, Any
from hh.gateway.registry.registry import register_action
from hh.gateway.registry.registry import register_command
from hh.gateway.gateway import get_gateway
from hh.gateway.registry.debug import get_trace_in, get_trace_out, get_log, get_debug, get_warn, register_debug_init
from hh.gateway.response.json_standard import success_payload
import subprocess
from hh.gateway.error.error_store import report_error, is_error

trace_in = lambda message=None: None
trace_out = lambda message=None: None
log = lambda message: None
debug = lambda message: None
warn = lambda message: None

@register_debug_init
def _initialize_debug():
    global trace_in, trace_out, log, debug, warn
    trace_in = get_trace_in(True)
    trace_out = get_trace_out(True)
    log = get_log(True)
    debug = get_debug(True)
    warn = get_warn(True)

def _iso_now() -> str:
    return datetime.datetime.utcnow().replace(microsecond=0).isoformat() + "Z"

def detect_project_name() -> str:
    """Detect project name from current directory."""
    try:
        gateway = get_gateway()
        if not gateway or not gateway.os:
            return "henhouse"
        cwd = gateway.os.get_cwd()
        if cwd.startswith('/srv/'):
            parts = cwd.split('/')
            if len(parts) >= 3:
                return parts[2]
        else:
            current_path = Path(cwd)
            while current_path != current_path.parent:
                hh_dir = current_path / 'hh'
                if hh_dir.exists() and hh_dir.is_dir():
                    return current_path.name
                current_path = current_path.parent
        return "henhouse"
    except Exception:
        return "henhouse"

def _install_config_path(project_name: str) -> Path:
    return Path(f"/root/.{project_name}-install.cnf")

def _manifest_remove_site(project_name: str, domain: str) -> None:
    cfg_path = _install_config_path(project_name)
    if not cfg_path.exists():
        return
    parser = configparser.ConfigParser()
    parser.read(cfg_path)
    if parser.has_section("manifest_sites") and parser.has_option("manifest_sites", domain):
        parser.remove_option("manifest_sites", domain)
        with open(cfg_path, 'w') as f:
            parser.write(f)
        os.chmod(cfg_path, 0o600)

def validate_nginx_config_for_deletion(config_file: Path, force: bool = False) -> bool:
    """Validate that an nginx config file was created by our deploy system."""
    trace_in()
    try:
        if not config_file.exists():
            warn(f"Config file {config_file} does not exist")
            trace_out()
            return False
        
        # Skip marker check if force is enabled
        if force:
            log(f"Force flag enabled - skipping deployment marker check for {config_file}")
            trace_out()
            return True
        
        # Check if file has our marker
        with open(config_file, 'r') as f:
            content = f.read()
        
        # Look for our deployment system markers
        has_deploy_marker = 'Generated by henhouse deploy-http system' in content or 'Generated by henhouse deploy-shttp system' in content
        
        if not has_deploy_marker:
            warn(f"Config file {config_file} does not have deployment marker - SKIPPING")
            debug(f"This config was not created by our deploy system - it may be manually configured")
            trace_out()
            return False
        
        log(f"Config file {config_file} passed safety checks")
        trace_out()
        return True
        
    except Exception as e:
        warn(f"Error validating config file {config_file}: {str(e)} - SKIPPING")
        trace_out()
        return False

def remove_nginx_config(domain: str, force: bool = False) -> bool:
    """Remove Nginx configuration for domain."""
    trace_in()
    try:
        # Safety check: validate the config file before deletion
        config_file = Path(f'/etc/nginx/sites-available/{domain}')
        if not validate_nginx_config_for_deletion(config_file, force):
            warn(f"Config file validation failed for {domain} - refusing to delete")
            trace_out()
            return False
        
        # Remove symlink from sites-enabled
        enabled_file = Path(f'/etc/nginx/sites-enabled/{domain}')
        if enabled_file.exists():
            enabled_file.unlink()
            log(f"Removed symlink: {enabled_file}")
        else:
            log(f"Symlink not found: {enabled_file}")
        
        # Remove config file from sites-available
        if config_file.exists():
            config_file.unlink()
            log(f"Removed config: {config_file}")
        else:
            log(f"Config file not found: {config_file}")
        
        # Test Nginx configuration
        test_result = subprocess.run(['nginx', '-t'], capture_output=True, text=True)
        if test_result.returncode != 0:
            warn(f"Nginx configuration test failed: {test_result.stderr}")
            trace_out()
            return False
        
        log("Nginx configuration test passed")
        
        # Reload Nginx
        reload_result = subprocess.run(['systemctl', 'reload', 'nginx'], capture_output=True, text=True)
        if reload_result.returncode != 0:
            # Try restart instead
            restart_result = subprocess.run(['systemctl', 'restart', 'nginx'], capture_output=True, text=True)
            if restart_result.returncode != 0:
                warn(f"Failed to reload/restart Nginx: {restart_result.stderr}")
                trace_out()
                return False
            log("Nginx restarted successfully")
        else:
            log("Nginx reloaded successfully")
        
        trace_out()
        return True
        
    except Exception as e:
        warn(f"Failed to remove Nginx configuration: {e}")
        trace_out()
        return False

@register_action('http_remove')
@register_command('http_remove')
def http_remove() -> bool:
    trace_in()
    gateway = get_gateway()
    if not gateway:
        warn("No gateway available")
        trace_out()
        return False

    # Get domain argument
    domain = gateway.get_arg('domain')
    if not domain:
        warn("Domain argument required")
        report_error("action", "Domain argument required")
        trace_out()
        return False
    
    # Check for force flag
    force = gateway.get_arg('force')
    if force:
        log("Force flag enabled - skipping safety checks")
    
    log(f"Starting HTTP removal for domain: {domain}")
    project_name = detect_project_name()
    log(f"Project: {project_name}")

    # Remove Nginx configuration
    config_removed = False
    try:
        if remove_nginx_config(domain, force):
            config_removed = True
            log("Nginx configuration removed successfully")
        else:
            warn("Nginx configuration removal failed")
            report_error("action", "Nginx configuration removal failed")
    except Exception as e:
        warn(f"Failed to remove Nginx configuration: {e}")
        report_error("action", f"Failed to remove Nginx configuration: {e}")

    # Check Nginx status
    status_result = subprocess.run(['systemctl', 'is-active', 'nginx'], 
                                   capture_output=True, text=True)
    nginx_active = status_result.returncode == 0 and status_result.stdout.strip() == 'active'

    # Final result
    result = not is_error()
    if result:
        log("HTTP removal completed successfully")
        result_data = {
            "domain": domain,
            "config_removed": config_removed,
            "nginx_active": nginx_active,
            "status": "removed"
        }
        try:
            _manifest_remove_site(project_name, domain)
        except Exception as e:
            warn(f"Failed to update manifest_sites: {e}")
        gateway.response.set_action_response(success_payload(result_data))
    else:
        log("HTTP removal encountered problems")

    # Clear registry cache
    from hh.deploy.cache.cache_cleanup_registry import clean_all_caches
    clean_all_caches()
    trace_out()
    return result

