SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `files`;
DROP TABLE IF EXISTS `images`;
DROP TABLE IF EXISTS `audio`;
DROP TABLE IF EXISTS `video`;
DROP TABLE IF EXISTS `pages`;

SET FOREIGN_KEY_CHECKS = 1;

