from typing import Protocol, Any, Dict, List, Optional, runtime_checkable

@runtime_checkable
class DatabaseConnection(Protocol):
    """Protocol for database connection objects"""
    def cursor(self) -> 'DatabaseCursor': ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...

@runtime_checkable  
class DatabaseCursor(Protocol):
    """Protocol for database cursor objects"""
    def execute(self, query: str, params: Optional[List[Any]] = None) -> None: ...
    def fetchone(self) -> Optional[Dict[str, Any]]: ...
    def fetchall(self) -> List[Dict[str, Any]]: ...
    def lastrowid(self) -> int: ...
